name: Scheduled Date Workflow

on: 
  schedule:
    - cron: '*/1 * * * *' 

jobs:
  scheduled_action:
  runs-on: ubuntu_latest
  steps:
    name: Echo current time on a schedule
    run: echo "The current server time is $(date)"